"""
=============================================================================
COMPONENT 4 — ML Classification Engine
=============================================================================
AI-Powered Phishing Detector | Cybersecurity Project
-----------------------------------------------------------------------------
ROLE IN PIPELINE:
    Trains machine learning models on the feature matrices produced by
    Component 3 and uses them to assign a threat probability score to
    each email.

    Two models are trained and compared:
        1. Logistic Regression  — fast, interpretable baseline
        2. Random Forest        — main classifier, more accurate

    In cybersecurity terms this component is the "detection engine":
    it generalizes from known phishing patterns to catch new, unseen
    attacks — including those generated by LLMs.

INPUTS:
    - X_train, y_train : feature matrix + labels for training
    - X_test,  y_test  : feature matrix + labels for evaluation

OUTPUTS:
    - Trained model objects (Logistic Regression + Random Forest)
    - Threat probability scores for every email in the test set
    - Saved model files in output/models/ for reuse in Component 5
=============================================================================
"""

import os
import pickle
import numpy as np
from sklearn.linear_model  import LogisticRegression
from sklearn.ensemble       import RandomForestClassifier
from sklearn.metrics        import (accuracy_score, precision_score,
                                    recall_score, f1_score,
                                    classification_report, confusion_matrix)


# ─── Model Configuration ──────────────────────────────────────────────────────

# Logistic Regression — interpretable baseline
LR_PARAMS = {
    "C":            1.0,       # regularization strength (lower = more regularized)
    "max_iter":     1000,      # iterations to converge
    "solver":       "lbfgs",
    "random_state": 42,
}

# Random Forest — main classifier
RF_PARAMS = {
    "n_estimators": 200,       # number of decision trees
    "max_depth":    None,      # trees grow until pure (no depth limit)
    "min_samples_split": 5,
    "random_state": 42,
    "n_jobs":       -1,        # use all CPU cores
}

# Classification threshold.
# Emails with threat probability >= this value are flagged as Phish.
# Lowering the threshold increases Recall (catches more phishing)
# at the cost of more false alarms. In security we prefer high Recall.
THREAT_THRESHOLD = 0.40


# ─── Training ─────────────────────────────────────────────────────────────────

def train_logistic_regression(X_train, y_train):
    """
    Train a Logistic Regression classifier on the training feature matrix.

    Logistic Regression outputs a probability between 0 and 1, which we
    use as the threat score. It is fast, interpretable, and a strong
    baseline for text classification tasks.

    Returns the fitted model.
    """
    print("[Classification] Training Logistic Regression ...")
    model = LogisticRegression(**LR_PARAMS)
    model.fit(X_train, y_train)
    print("    Logistic Regression training complete.")
    return model


def train_random_forest(X_train, y_train):
    """
    Train a Random Forest classifier on the training feature matrix.

    Random Forest builds many decision trees on random subsets of the data
    and takes a majority vote. It handles non-linear patterns and feature
    interactions better than Logistic Regression, making it more effective
    against diverse phishing styles.

    Returns the fitted model.
    """
    print("[Classification] Training Random Forest ...")
    model = RandomForestClassifier(**RF_PARAMS)
    model.fit(X_train, y_train)
    print("    Random Forest training complete.")
    return model


# ─── Prediction ───────────────────────────────────────────────────────────────

def predict(model, X, threshold=THREAT_THRESHOLD):
    """
    Run the trained model on a feature matrix and return:
        - threat_probs  : probability of being Phish (float, 0.0–1.0)
        - threat_labels : binary verdict (1=Phish, 0=Ham) based on threshold

    Using a threshold below 0.5 deliberately biases the model toward
    flagging borderline emails as Phish — in security, missing a real
    phishing email (False Negative) is more costly than a false alarm.
    """
    threat_probs  = model.predict_proba(X)[:, 1]          # column 1 = Phish probability
    threat_labels = (threat_probs >= threshold).astype(int)
    return threat_probs, threat_labels


# ─── Evaluation ───────────────────────────────────────────────────────────────

def evaluate_model(model_name, y_true, y_pred, y_proba=None):
    """
    Compute and print security evaluation metrics for a model.

    Metrics explained in security terms:
        Accuracy  — overall % of correct classifications
        Precision — of all emails flagged as Phish, how many were real threats?
                    (low precision = too many false alarms)
        Recall    — of all real phishing emails, how many did we catch?
                    (low recall = missed attacks — the most dangerous failure)
        F1-Score  — harmonic mean of Precision and Recall

    Returns a dict of metric values.
    """
    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec  = recall_score(y_true, y_pred, zero_division=0)
    f1   = f1_score(y_true, y_pred, zero_division=0)
    cm   = confusion_matrix(y_true, y_pred)

    tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (0, 0, 0, 0)

    print(f"\n{'=' * 50}")
    print(f"  {model_name} — Security Evaluation Report")
    print(f"{'=' * 50}")
    print(f"  Accuracy  : {acc:.4f}  ({acc*100:.1f}%)")
    print(f"  Precision : {prec:.4f}  ({prec*100:.1f}%)")
    print(f"  Recall    : {rec:.4f}  ({rec*100:.1f}%)")
    print(f"  F1-Score  : {f1:.4f}")
    print(f"\n  Confusion Matrix:")
    print(f"              Predicted Ham   Predicted Phish")
    print(f"  Actual Ham      {tn:>6}           {fp:>6}   (False Positives)")
    print(f"  Actual Phish    {fn:>6}           {tp:>6}   (Detected Attacks)")
    print(f"\n  Missed attacks (False Negatives): {fn}")
    print(f"  False alarms   (False Positives): {fp}")
    print(f"\n  Full classification report:")
    print(classification_report(y_true, y_pred,
                                 target_names=["Ham (safe)", "Phish (threat)"],
                                 zero_division=0))

    return {
        "model":     model_name,
        "accuracy":  acc,
        "precision": prec,
        "recall":    rec,
        "f1":        f1,
        "tn": tn, "fp": fp, "fn": fn, "tp": tp,
    }


def compare_models(results_list):
    """
    Print a side-by-side comparison table of all evaluated models.
    """
    print("\n" + "=" * 65)
    print("  MODEL COMPARISON — Security Detection Performance")
    print("=" * 65)
    print(f"  {'Model':<30} {'Accuracy':>9} {'Precision':>10} {'Recall':>8} {'F1':>8}")
    print("-" * 65)
    for r in results_list:
        print(f"  {r['model']:<30} {r['accuracy']:>8.3f}  {r['precision']:>9.3f}  "
              f"{r['recall']:>7.3f}  {r['f1']:>7.3f}")
    print("=" * 65)
    # Highlight best model by Recall (most important in security)
    best = max(results_list, key=lambda x: x["recall"])
    print(f"\n  Best model by Recall (fewest missed attacks): {best['model']}")


# ─── Model Persistence ────────────────────────────────────────────────────────

def save_model(model, filename):
    """Save a trained model to disk using pickle."""
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    with open(filename, "wb") as f:
        pickle.dump(model, f)
    print(f"  Saved → {filename}")


def load_model(filename):
    """Load a trained model from disk."""
    with open(filename, "rb") as f:
        return pickle.load(f)


# ─── Full training + evaluation pipeline ──────────────────────────────────────

def run_classification(X_train, X_test, y_train, y_test,
                       threshold=THREAT_THRESHOLD, save=True):
    """
    Train both models, evaluate them, compare results, and optionally save.

    Args:
        X_train, X_test : feature matrices from Component 3
        y_train, y_test : threat label arrays
        threshold       : classification threshold for Phish
        save            : whether to save models to output/models/

    Returns:
        lr_model  : trained Logistic Regression
        rf_model  : trained Random Forest
        results   : list of evaluation metric dicts
    """
    # ── Train ─────────────────────────────────────────────────────────────────
    lr_model = train_logistic_regression(X_train, y_train)
    rf_model = train_random_forest(X_train, y_train)

    # ── Predict ───────────────────────────────────────────────────────────────
    lr_proba, lr_preds = predict(lr_model, X_test, threshold)
    rf_proba, rf_preds = predict(rf_model, X_test, threshold)

    # ── Evaluate ──────────────────────────────────────────────────────────────
    lr_results = evaluate_model("Logistic Regression", y_test, lr_preds, lr_proba)
    rf_results = evaluate_model("Random Forest",       y_test, rf_preds, rf_proba)

    compare_models([lr_results, rf_results])

    # ── Save ──────────────────────────────────────────────────────────────────
    if save:
        print("\n[Classification] Saving models ...")
        save_model(lr_model, "output/models/logistic_regression.pkl")
        save_model(rf_model, "output/models/random_forest.pkl")

        # Save test predictions for Component 5
        import pandas as pd
        preds_df = pd.DataFrame({
            "y_true":       y_test,
            "lr_proba":     lr_proba,
            "lr_pred":      lr_preds,
            "rf_proba":     rf_proba,
            "rf_pred":      rf_preds,
        })
        os.makedirs("output", exist_ok=True)
        preds_df.to_csv("output/predictions.csv", index=False)
        print("  Saved → output/predictions.csv")

    return lr_model, rf_model, [lr_results, rf_results]


# ─── Demo ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print(" COMPONENT 4 — ML Classification Engine")
    print("=" * 60)

    import pandas as pd
    import sys
    import os
    sys.path.insert(0, os.path.dirname(__file__))

    from component2_preprocessing  import preprocess_dataframe
    from component3_feature_extraction import build_feature_matrices

    if os.path.exists("output/train_clean.csv") and os.path.exists("output/test.csv"):
        train_df = pd.read_csv("output/train_clean.csv")
        test_df  = preprocess_dataframe(pd.read_csv("output/test.csv"))

        X_train, X_test, y_train, y_test, _ = build_feature_matrices(train_df, test_df)
        run_classification(X_train, X_test, y_train, y_test)
    else:
        print("[INFO] No dataset found. Run component1 first to generate output/train.csv")
        print("       Running a quick synthetic smoke-test instead ...\n")

        # Minimal synthetic test to verify the module works
        from scipy.sparse import csr_matrix
        np.random.seed(42)
        X = csr_matrix(np.random.rand(100, 50))
        y = np.array([1]*50 + [0]*50)

        X_tr, X_te = X[:80], X[80:]
        y_tr, y_te = y[:80], y[80:]

        run_classification(X_tr, X_te, y_tr, y_te, save=False)
